fieldLayouts:
  6d355201-ed8b-4ca4-b04e-68e1494b44d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 38a6be02-9c55-4e51-9234-5077b9470308
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93bd28f6-9598-4043-9a96-641ba7662e24
        userCondition: null
fs: StoreProductPhotos
handle: productPhoto
name: 'product photo'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: StoreProductPhotos
transformSubpath: ''
