columnSuffix: hvjlefrx
contentColumnType: 'decimal(12,2)'
fieldGroup: f733e2e4-8e14-49b4-bf50-5b0cc5efc7c2 # Common
handle: price
instructions: null
name: Price
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: EUR
  previewFormat: currency
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
