defaultPlacement: end
enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  31345414-3347-4646-a236-349eb065e547: # examen-sieme
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
